version: '3.9'

networks:
  mutant-net:
    driver: bridge

services:
  server:
    build:
      context: ./mutant-server
      dockerfile: Dockerfile
      target: mutant_server
    volumes:
      - ./mutant-server/:/mutant-server/
      - index_data:/index_data
    command: uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CLICKHOUSE_TCP_PORT=9000
    ports:
      - 8000:8000
    depends_on:
      - clickhouse
      - redis
    networks:
      - mutant-net

  worker:
    build:
      context: ./mutant-server
      dockerfile: DockerfileCelery
    command: celery worker --app=mutant_server.worker.celery --loglevel=info
    volumes:
      - ./mutant-server/:/mutant-server/
      - index_data:/index_data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - server
      - redis
    networks:
      - mutant-net

  clickhouse:
    image: docker.io/bitnami/clickhouse:22.9
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/bitnami/clickhouse
      - backups:/backups
      - ./config/backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
    networks:
      - mutant-net

  redis:
    image: redis:6-alpine
    networks:
      - mutant-net

volumes:
  clickhouse_data:
    driver: local
  index_data:
    driver: local
  backups:
    driver: local