version: '3.9'

networks:
  net:
    driver: bridge

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./mutantdb/:/mutantdb/
      - index_data:/index_data
    command: uvicorn mutantdb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      - MUTANT_DB_IMPL=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    ports:
      - 8000:8000
    depends_on:
      - clickhouse
    networks:
      - net

  clickhouse:
    image: clickhouse/clickhouse-server:22.9-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/bitnami/clickhouse
      - backups:/backups
      - ./config/backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
    networks:
      - net

volumes:
  clickhouse_data:
    driver: local
  index_data:
    driver: local
  backups:
    driver: local