version: '3.9'

networks:
  my-network:
    driver: bridge

services:
  server:
    build:
      context: ./mutant-server
      dockerfile: Dockerfile
    volumes:
      - ./mutant-server/:/mutant-server/
    command: uvicorn mutant_server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    # env_file:
    #   - ./mutant-server/.env
    ports:
      - 8000:8000
    depends_on:
      - clickhouse
    networks:
      - my-network

  clickhouse:
    image: docker.io/bitnami/clickhouse:22.9
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/bitnami/clickhouse
    networks:
      - my-network

volumes:
  clickhouse_data:
    driver: local