version: '3.9'

networks:
  mutant-net:
    driver: bridge

services:
  server_test:
    build:
      context: .
      dockerfile: Dockerfile
      target: mutant_server_test
    volumes:
      - ./:/mutant-server/
      - index_data:/index_data
    depends_on:
      - clickhouse_test
    networks:
      - mutant-net

  clickhouse_test:
    image: docker.io/bitnami/clickhouse:22.9
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8124:8124'
      - '9008:9008'
    networks:
      - mutant-net

volumes:
  index_data:
    driver: local
