version: '3.9'

networks:
  mutant-net:
    driver: bridge

services:
  server_test:
    build:
      context: .
      dockerfile: Dockerfile
      target: mutant_server_test
    volumes:
      - ./:/mutant-server/
      - index_data:/index_data
    depends_on:
      - clickhouse
    networks:
      - mutant-net

  clickhouse:
    image: docker.io/bitnami/clickhouse:22.9
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8123:8123'
      - '9000:9000'
    networks:
      - mutant-net

volumes:
  index_data:
    driver: local
