name: Mutant Server Test

on:
    push:
      branches:
        - main
      paths:
        - 'mutant-server/**'
    pull_request:
      branches:
        - main
      paths:
        - 'mutant-server/**'
jobs:
    test:
        strategy:
            matrix:
                python: ['3.10']
                platform: [ubuntu-latest]
        runs-on: ${{ matrix.platform }}
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Test
          run: bin/test