name: Mutant Server Test

on:
    push:
      branches:
        - main
      paths:
        - 'mutant-server/**'
    pull_request:
      branches:
        - main
      paths:
        - 'mutant-server/**'
jobs:
    test:
        strategy:
            matrix:
                python: ['3.11']
                platform: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.platform }}
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python }}
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python }}
        - name: Install test dependencies
          run: cd mutant-server && python -m pip install -r requirements.txt -r requirements_dev.txt
        - name: Test
          run: cd mutant-server && python -m pytest