name: Mutant Release

on:
  push:
    tags:
      - '*'
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "ghcr.io/mutant/mutant-server"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Client Dev Dependencies
      run: cd mutant-client && python -m pip install -r dev_requirements.txt
    - name: Build Client
      run: cd mutant-client && python -m build

    - name: Log in to the Container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Install setuptools_scm
      run: cd mutant-server && python -m pip install setuptools_scm
    - name: Get Docker Tag
      id: tag
      run: cd mutant-server && echo "tag_name=$IMAGE_NAME:$(bin/version)" >> $GITHUB_OUTPUT
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: mutant-server
        push: true
        tags: ${{ steps.tag.outputs.tag_name}}
    - name: Get Release Version
      id: version
      run: cd mutant-client && echo "version=$(python -m setuptools_scm)" >> $GITHUB_OUTPUT
    - name: Get current date
      id: builddate
      run: echo "builddate=$(date +'%Y-%m-%dT%H:%M')" >> $GITHUB_OUTPUT
    - name: Release Tagged Version
      uses: ncipollo/release-action@v1.11.1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: |
          Version: `${{steps.version.outputs.version}}`
          Git ref: `${{github.ref}}`
          Build Date: `${{steps.builddate.outputs.builddate}}`
          PIP Package: `mutant_client-${{steps.version.outputs.version}}.tar.gz`
          Docker Image: `${{steps.tag.outputs.tag_name}}`
        artifacts: "mutant-client/dist/mutant_client-${{steps.version.outputs.version}}.tar.gz"
        prerelease: true
    - name: Update Tag
      uses: richardsimko/update-tag@v1.0.5
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      with:
        tag_name: latest
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release Latest
      uses: ncipollo/release-action@v1.11.1
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      with:
        tag: "latest"
        name: "Latest"
        body: |
          Version: `${{steps.version.outputs.version}}`
          Git ref: `${{github.ref}}`
          Build Date: `${{steps.builddate.outputs.builddate}}`
          PIP Package: `mutant_client-${{steps.version.outputs.version}}.tar.gz`
          Docker Image: `${{steps.tag.outputs.tag_name}}`
        artifacts: "mutant-client/dist/mutant_client-${{steps.version.outputs.version}}.tar.gz"
        allowUpdates: true
        prerelease: true